env: dev11
spring:
  application:
    name: order
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://106.13.217.198:8761/eureka/

server:
  port: 8081
